#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x1425F8CE5EBA0E07 (shimizukawa@gmail.com)
#
Name     : deprecated-sphinxcontrib-websupport
Version  : 1.1.0
Release  : 26
URL      : http://pypi.debian.net/sphinxcontrib-websupport/sphinxcontrib-websupport-1.1.0.tar.gz
Source0  : http://pypi.debian.net/sphinxcontrib-websupport/sphinxcontrib-websupport-1.1.0.tar.gz
Source99 : http://pypi.debian.net/sphinxcontrib-websupport/sphinxcontrib-websupport-1.1.0.tar.gz.asc
Summary  : Sphinx API for Web Apps
Group    : Development/Tools
License  : BSD-2-Clause
Requires: deprecated-sphinxcontrib-websupport-license = %{version}-%{release}
Requires: deprecated-sphinxcontrib-websupport-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
===================================
===================================
This is the Sphinx documentation generator, see http://www.sphinx-doc.org/.

%package legacypython
Summary: legacypython components for the deprecated-sphinxcontrib-websupport package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-sphinxcontrib-websupport package.


%package license
Summary: license components for the deprecated-sphinxcontrib-websupport package.
Group: Default

%description license
license components for the deprecated-sphinxcontrib-websupport package.


%package python
Summary: python components for the deprecated-sphinxcontrib-websupport package.
Group: Default

%description python
python components for the deprecated-sphinxcontrib-websupport package.


%prep
%setup -q -n sphinxcontrib-websupport-1.1.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554328923
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-sphinxcontrib-websupport
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-sphinxcontrib-websupport/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-sphinxcontrib-websupport/LICENSE

%files python
%defattr(-,root,root,-)
